package com.java.exceptionhandling;
//
//public class ExceptionViolation {
//
//    public static void main(String[] args) {
//
//        try {
//            System.out.println(9 / 0);
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//        System.out.println("This is one of the worst practices ");
//////////////////////////////////////////////////////
//        try {
//            System.out.println(10 / 0);
//
//        } catch (ArithmeticException e) {
//            e.printStackTrace();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//////////////////////////////////////////////////
//        try {
//            System.out.println("myname");
//            System.out.println(9 / 0);
//            try {
//                System.out.println("premsai");
//
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
//
//        }
//////////////example for finally
//
//            try {
//                System.out.println("establish data base connection");
//                System.out.println("read data");
//                //System.exit(0);
//            } catch (Exception e) {
//                e.printStackTrace();
//                //write some alteernate code
//
//            } finally {
//                System.out.println("close data base connection");
//            }
//        }
//    }
//}
